replicaCount: 2

image:
  repository: movses555/simple-web-project
  tag: 5a9bf8dd792c4959cd8d1b69c27b9a2b51ad209b
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 31600
  targetPort: 80
  port: 80

